### ISSUE TITLE
微信分享参数限制 建议在ShareSDK中处理一下~ 

### ISSUE THREAD

**Issue by careylee0127** [xyzlf/ShareSDK#11]
如题~ 测试发现有些内容无法分享出去 无法调起微信界面~ 查看日志微信打印log~ checkArgs fail, description is invalid~ 查看微信代码在WXMediaMessage发现如下代码~ 
final boolean checkArgs() {
        if(this.getType() != 8 || this.thumbData != null && this.thumbData.length != 0) {
            if(this.getType() == 36 && (this.thumbData == null || this.thumbData.length > 131072)) {
                Log.e("MicroMsg.SDK.WXMediaMessage", "checkArgs fail, thumbData should not be null or exceed 128kb");
                return false;
            } else if(this.getType() != 36 && this.thumbData != null && this.thumbData.length > '耀') {
                Log.e("MicroMsg.SDK.WXMediaMessage", "checkArgs fail, thumbData is invalid");
                return false;
            } else if(this.title != null && this.title.length() > 512) {
                Log.e("MicroMsg.SDK.WXMediaMessage", "checkArgs fail, title is invalid");
                return false;
            } else if(this.description != null && this.description.length() > 1024) {
                Log.e("MicroMsg.SDK.WXMediaMessage", "checkArgs fail, description is invalid");
                return false;
            } else if(this.mediaObject == null) {
                Log.e("MicroMsg.SDK.WXMediaMessage", "checkArgs fail, mediaObject is null");
                return false;
            } else if(this.mediaTagName != null && this.mediaTagName.length() > 64) {
                Log.e("MicroMsg.SDK.WXMediaMessage", "checkArgs fail, mediaTagName is too long");
                return false;
            } else if(this.messageAction != null && this.messageAction.length() > 2048) {
                Log.e("MicroMsg.SDK.WXMediaMessage", "checkArgs fail, messageAction is too long");
                return false;
            } else if(this.messageExt != null && this.messageExt.length() > 2048) {
                Log.e("MicroMsg.SDK.WXMediaMessage", "checkArgs fail, messageExt is too long");
                return false;
            } else {
                return this.mediaObject.checkArgs();
            }
        } else {
            Log.e("MicroMsg.SDK.WXMediaMessage", "checkArgs fail, thumbData should not be null when send emoji");
            return false;
        }
    }

**Comment by xyzlf** [comment]
好的，我来处理下。 看来微信对分享文案，分享标题的长度，都做了限制...
