### ISSUE TITLE
不解之处

### ISSUE THREAD

**Issue by diasstant-ht** [xyzlf/ShareSDK#13]
点击微博分享，进入微博分享的界面，然后点击取消，走的是微博分享成功的回调。

**Comment by xyzlf** [comment]
因为没有用到微博的SDK，直接打开微博App了， 这样就拿不到回调状态， 提示文案需要删除。

为啥去掉微博的SDK？？ 1、不需要去官方开放平台注册账号。2、可以减小分享aar库的大小。 3、之前的aar使用了微博的SDK，有童鞋反馈有兼容bug。 4、最近才删除了微博SDK的。

**Comment by xyzlf** [comment]
补充一点： 微博SDK只能调用官方微博完整版本， 微博还有个轻聊版本， 如果用微博官方SDK， 就没有办法兼顾到轻聊版本。

现在这样的处理方式， 你安装微博完整版， 安装微博轻聊版， 都能同时兼容分享。

**Comment by diasstant-ht** [comment]
我要根据分享的回调处理后面的事情啊。我该怎么解决这个问题啊？

**Comment by xyzlf** [comment]
你用 0.0.7的aar版本吧。   但是你记得去微博官方平台申请一个开发者key....

**Comment by diasstant-ht** [comment]
0.07到0.09有什么改进吗？

**Comment by xyzlf** [comment]
0.0.7到0.0.9， 1、去除了微博的SDK， 不需要申请key。2、解了几个小bug。3、其他改动不大....

使用方式完全一样。

**Comment by xyzlf** [comment]
![image](https://user-images.githubusercontent.com/6000780/29447925-be9a4078-8426-11e7-8fa1-396eadd10694.png)
用0.0.7的aar，记得添加微博的key

android:name="sina_weibo_redirecturi"  android:value="@string/sina_weibo_redirecturi" 

android:name="sina_weibo_key"    android:value="@string/sina_weibo_key"

**Comment by diasstant-ht** [comment]
我现在只需要把那个0.0.9改成0.0.7  ，  然后把你截图的东西写到AndroidManifest.xml文件里面，把里面的参数改一下就可以了是吧？

**Comment by xyzlf** [comment]
是的~

**Comment by diasstant-ht** [comment]
![image](https://user-images.githubusercontent.com/30858954/29448305-96fc76d8-8428-11e7-9c47-a393a4fe7be3.png)
我把0.09改成0.07      点击微博分享就崩溃了，这个是什么原因？（我AndroidManifest.xml还没配置）

**Comment by diasstant-ht** [comment]
改了之后微信就分享不了了，
![image](https://user-images.githubusercontent.com/30858954/29448457-52ba3720-8429-11e7-89ee-acc328fa8b8c.png)

**Comment by xyzlf** [comment]
1、微博崩溃的问题， 原因是， 不能隐士调用微博的service，必须显示调用。 真坑爹，这个是微博sdk里面的内容，需要对微博jar包进行修改。 可能得重新去微博官方升级它的sdk看看了。

2、微信分享不了， 它已经告诉你原因了， 你的应用没有通过审核。 或者你打的包，不是release签名版本，是debug签名版本。

**Comment by diasstant-ht** [comment]
微信的我知道谁什么情况了，但是微博的，   我该怎么修改啊才能快速的解决这个问题。

**Comment by diasstant-ht** [comment]
微信的我知道是什么情况了，但是微博的， 我该怎么修改啊才能快速的解决这个问题。

**Comment by xyzlf** [comment]
https://github.com/sinaweibosdk/weibo_android_sdk  微博sdk， 3.2开始，用全新方式改版了....  你下拉我的代码， 把微博那块替换掉吧， 我现在没空改。

**Comment by diasstant-ht** [comment]
我不知道改哪一块的东西。也不知道复制哪一块的东西。尴尬的一批。。。。。
