### ISSUE TITLE
微信提示：由于不支持的分享类型，无法分享

### ISSUE THREAD

**Issue by zj2050** [xyzlf/ShareSDK#14]
程序签名了，也在微信平台注册，且审核通过，但分享的时候上面的文字提示 由于不支持的分享类型，无法分享， 但下面的按钮是”返回（未审核的应用）“ ， 只需要填写appkey， 不需要开放平台的微信appid吗？

另外，我修改过开放平台的app 的签名数据， 但提示是审核通过状态啊

谢谢

**Comment by xyzlf** [comment]
1、需要填写微信开放平台的key。 你看微信开放平台SDK源码如下：
public static IWXAPI createWXAPI(Context var0, String var1) {
    return createWXAPI(var0, var1, false);
}
public static IWXAPI createWXAPI(Context var0, String var1, boolean var2) {
    a.c("MicroMsg.PaySdk.WXFactory", "createWXAPI, appId = " + var1 + ", checkSignature = " + var2);
    return new WXApiImplV10(var0, var1, var2);
}

2、你这种情况，之前也有童鞋问我，他们遇到的情况是，微信开放平台信息同步问题。 隔一天再试一下...

3、微信分享比较要注意的几个坑是：
（1）需要有 pkgname.wxapi.WXEntityActivity.java 这个类。
（2）必须是正式签名包。
（3）填写微信开放平台的appkey。 
可参照这里：http://xyzlf.github.io/2016/07/01/android-share-sdk-1.html 

然后，就没啥需要注意的了。

**Comment by xyzlf** [comment]
补充一点：如果你之前试过debug签名的包分享。 重新测试前，记得将微信数据清除了，或者卸载微信，重新安装下。

**Comment by zj2050** [comment]
@xyzlf  谢谢， key在 mainf 的meta 里面设置了， 那开放平台对应的appid 在哪儿设置，你的demo里面也没有看到如何设置呢

**Comment by xyzlf** [comment]
开放平台的appid就是设置在 manifest.xml里面呀， 你写的key，是哪里的key呀？也是开放平台的么？

如果都是微信开放平台的，你换一下，在manifest.xml里面，替换成appid，再重新打包试一下。从微信sdk日志看，需要填写appid。看sdk的API，只要一个参数即可...

**Comment by zj2050** [comment]
@xyzlf          <meta-data
            android:name="weixin_key"
            android:value="@string/weixin_key"/>

**Comment by zj2050** [comment]
@xyzlf 
        <meta-data
            android:name="weixin_key"
            android:value="@string/weixin_key"/>

开放平台里面有两个值：
AppID：wxbf16ed405e9384fa
AppSecret： 
 
你那个地方填写哪个？

**Comment by xyzlf** [comment]
你填写 appid， appsecret是微信登录用到的。 好了，你把上面的Appid删除了吧...这是你App的隐私信息

**Comment by zj2050** [comment]
@xyzlf 
谢谢，我试一下

可以了，感谢，我一直在拿另外一个测试，浪费啊

**Comment by Fxiu** [comment]
weixin_key到底是那个值

**Comment by xyzlf** [comment]
@Fxiu 微信开放平台申请后，填这个值：appid

**Comment by Fxiu** [comment]
@xyzlf 成了，谢谢
