### ISSUE TITLE
分享大图

### ISSUE THREAD

**Issue by xxxiaokay** [xyzlf/ShareSDK#16]
你好,请问你做这个分享大图的功能具体使用到sharesdk的是什么api?我直接集成sharesdk分享本地图片总 感觉被压缩了

**Comment by xyzlf** [comment]
会压缩的，但是不压缩，会分享失败，微信对分享图片的大小有限制。

**Comment by xyzlf** [comment]
ShareByWeixin.java   shareImg()方法

**Comment by xxxiaokay** [comment]
感谢回复,我现在遇到的一个情况是这样的,
用sharesdk的setImageData传Bitmap分享到微信,图片的分辨率没有问题,
可是用setIamgePath传图片路径分享到微信和qq,图片分辨率都缩小了将近一半,
所以才想请教你看看是什么api分享本地图片才好

**Comment by xyzlf** [comment]
public Bitmap getLoacalBitmap(String localPath) {
        File file = new File(localPath);
        if (file.exists()) {
            try {
                return BitmapFactory.decodeFile(localPath);
            } catch (OutOfMemoryError error) {
                error.printStackTrace();
            }
        }
        return BitmapFactory.decodeResource(context.getResources(), R.drawable.share_default);
    }

好像也没啥特殊的，我就是根据你的url获取本地图片， 拿到bitmap后，进行统一压缩，分享的。   你可以瞅瞅代码.... 总共没几行代码....

**Comment by xxxiaokay** [comment]
好的,谢谢
