### ISSUE TITLE
跳出对话框，点击微信图标后，对话框不消失，微信闪退，申请微信id时，证书指纹用的是SHA1值。

### ISSUE THREAD

**Issue by admingalery** [xyzlf/ShareSDK#19]

**Comment by xyzlf** [comment]
参照文章中微信问题部分：
http://xyzlf.cn/2016/07/01/android-share-sdk-1.html

以往的经验：
1、检查填写的AppId是不是正确，不是AppSecret。
2、当天申请的一般微信服务会有延迟，等一两天就好了。
