### ISSUE TITLE
考虑过把三方登录也集成进来么

### ISSUE THREAD

**Issue by hike2008** [xyzlf/ShareSDK#2]

**Comment by xyzlf** [comment]
第三方登录，比如微信登录，微博登录，这些SDK中应该也包含了相应API。目前没考虑这块...可以考虑加！但是需要有使用场景，这个SDK，我们项目再用，可以保证不断完善。没有使用场景，就类似Demo了..

**Comment by hike2008** [comment]
嗯, 那我自己在你的基础上加三方登录, 感觉用ShareSDK或者umeng太重了

**Comment by xyzlf** [comment]
不重吧...这里分享只是包装了一层....你如果需要微信、qq、微博，你可以在这基础上复用。如果只需要一种登录，那你自己去官网找SDK加入就行啦。

**Comment by hike2008** [comment]
我是说那个ShareSDK, 不是这个哈... 好吧, 名字重了

**Comment by hike2008** [comment]
Mob 和 Umeng, 这样是不是不会误解了, ㄟ(⊙ω⊙ㄟ)哈

**Comment by xyzlf** [comment]
哈哈哈...  你们有分享需求的话，可以用这个嘞，有啥使用不方便的地方，可以提pr，一块完善...

**Comment by hike2008** [comment]
嗯, 暂时用的Mob, 等在你的基础上加好了三方登录, 再一起替换

**Comment by xyzlf** [comment]
嗯嗯，详细使用文档，工程下面有.....有任何问题，都可以提pr，或者给我邮件。
