### ISSUE TITLE
关于jar包的问题

### ISSUE THREAD

**Issue by SmarterZys** [xyzlf/ShareSDK#20]
您好：关于shareLIbrary中的jar包有一些问题一直想不通
libs目录下目前有2个jar包：libammsdk-2.0.jar是微信分享的jar包，open_sdk_r5756_lite是QQ分享的jar包，但是项目中集成了sina_weibo的分享，我按照官方文档没有找到具体的jar包或者依赖，请问一下具体是怎么做到的呢

**Comment by xyzlf** [comment]
1、没用到新浪微博的jar，是因为之前的老jar包，有bug。然后去除了，使用直接打开新浪微博的方式进行分享。
2、如果要依赖新浪微博的jar，直接新浪微博官网，依赖它的aar就行了。新版的aar依赖比较方便。

**Comment by SmarterZys** [comment]
非常感谢
