### ISSUE TITLE
可以自定义分享渠道吗？比如支付宝的朋友圈或钉钉

### ISSUE THREAD

**Issue by admingalery** [xyzlf/ShareSDK#22]
希望可以自定义分享渠道，或者有自定义的文档。

**Comment by xyzlf** [comment]
目前里面，没有继承支付宝，钉钉相关的分享SDK。

这个分享SDK目前只有 QQ，微博，微信，朋友圈，短信，系统几个分享功能。这些功能是可以自定义展示的，使用文档里面有。
