### ISSUE TITLE
新浪微博引用不到类

### ISSUE THREAD

**Issue by kevinStrange** [xyzlf/ShareSDK#24]
大佬，你的weibo.sdk:core版本是多少，我这边在自己的项目中需要实现新浪微博第三方登录，可是没有办法引用到SsoHandler和Oauth2AccessToken这两个类

**Comment by xyzlf** [comment]
我没用到 微博 的SDK，我去掉了， 你自己引入一个微博的SDK就行了。

我用的方式，就是打开微博App进行分享的方式，没有微博App就没法进行分享。

**Comment by kevinStrange** [comment]
有时间的话，可以完善一下，这样用起来也很爽，也是顺便造福大家，当然这只是建议

**Comment by xyzlf** [comment]
之前有建议加上第三方登录功能的，目前没有业务场景，加上了可能会有bug。 这些分享功能是经历过业务验证的，所以开源出来了..
有需要的可以在此基础上去封装一下。
