### ISSUE TITLE
ShareHandlerActivity错误NoClassDefFoundError

### ISSUE THREAD

**Issue by swxca** [xyzlf/ShareSDK#3]
我把你的moudle导入我的项目，结果报这个 错。。。。。

**Comment by xyzlf** [comment]
你是clone代码，module依赖，还是gradle依赖？？

compile ('com.xyzlf.share:sharesdk:0.0.4') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
}
按照这样使用，就不会出现这个问题。你要是clone代码，module依赖，可能是你依赖的问题？

**Comment by swxca** [comment]
我项目依赖，之前NoClassDefFoundError的原因找到了，是因为你的项目的jar和我的冲突，我就provided了微博的jar，现在我compile了微博的就好了。可以找到ShareHandlerActivity，但是点了qq分享界面没反应，过一会儿自动分享取消。。我怀疑是qqlite.jar有问题，还有为什么导入的不是open_sdk而是QQlite。

**Comment by xyzlf** [comment]
open_sdk更大啊，为了aar小一点，qqlite也是官方最新的，就分享而言，是没有问题。

这个SDK已经在使用当中，经过验证，功能使用都是正常的。

你项目依赖应该很方便调试的，看看是不是数据源的问题。如果发现确实SDK的问题，可以给我提PR...或者告之，我修复它..

**Comment by swxca** [comment]
为什么每次点了都是取消分享呀。。这个库的问题是，你没有集成第三方登录，那么我自己集成了第三方登录，然后用你的分享，两个moudle的JAR就会冲突，版本还可能不一致，那么到底是用哪个版本呢？如果用了你的版本，那登录的代码就可能失效。总之，都是SDK的问题。

**Comment by xyzlf** [comment]
1.不要可能，代码你都有，不能调试么？
2.很简单，你啊把qq，微博的jar用一份，都用你的，或者都用分享sdk的，不就解决了。
3.总之是sdk问题，你也没描述清楚。这样能解决问题？

**Comment by xyzlf** [comment]
我的jar也都是qq，微博，官方网站下载的，你不放心，重新下载一份，放里面，登录和分享用一份就是了。为啥要保持两份，有冲突，具体问题又没找出来。

**Comment by swxca** [comment]
多谢你啦。问题找到了，第一获取appID那里有点问题，会获得到null字符串，具体我没看，明天再改。第二，就是SDK版本问题，我不知道为什么我用最新版本qq登录会没反应。第三是moudle依赖，为了防止jar冲突，第一个jar导入了，重复的用provided而不是compile。最后谢谢。
