### ISSUE TITLE
只分享图片可以吗？

### ISSUE THREAD

**Issue by tdxtxt** [xyzlf/ShareSDK#4]
只分享图片可以吗？

**Comment by xyzlf** [comment]
你说的情况应该是针对微信吧？
1、微博的话，你不填文案，就行了。
2、微信只分享大图，里面有方法，但是没封装调用处，你可以看下这个类 ShareByWeixin  下面有个只分享大图的方法....你自己整合整合下，我今天有点忙，有空的时候，我想想怎么整合出一个好用的调用方法。

**Comment by xyzlf** [comment]
你可以在调用处这样使用：
ShareByWeixin shareByWeixin = new ShareByWeixin(this, ShareConstant.SHARE_CHANNEL_WEIXIN_CIRCLE);
shareByWeixin.registerWeixinReceiver();
shareByWeixin.shareImg(Bitmap bitmap, OnShareListener listener); //这方法是只分享大图

调用完记得unregisterWeixinReceiver();

**Comment by xyzlf** [comment]
你好！ 我在 0.0.7里面加入了大图分享，也就是你说的只分享一张图片，如果有需要，可以使用看看。有任何问题，欢迎提Issues。
