### ISSUE TITLE
build successful,but have some errors,how to solve?

### ISSUE THREAD

**Issue by xeon2007** [xyzlf/ShareSDK#5]
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.tencent.mm.sdk.b.b) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.

**Comment by xyzlf** [comment]
Just ignore.

**Comment by xeon2007** [comment]
why not slove it，i tried to turn lint off and keep proguard rules about innerclasses，but they are useless.

**Comment by xyzlf** [comment]
I don't know how to solve the warning.   I tried to solve it to add proguard rules . The warning is from the  : [weixin sdk](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419319167&token=&lang=zh_CN )
