### ISSUE TITLE
请问下下面的错误是与第三方支付的包冲突了吗？怎么解决呢、、

### ISSUE THREAD

**Issue by love-311** [xyzlf/ShareSDK#6]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK com/tencent/mm/sdk/platformtools/rep5402863540997075488.tmp
	File1: C:\Users\Administrator\.android\build-cache\3ea4306d89f3d4f6c520363c0fe7c88eb50a3d63\output\jars\classes.jar
	File2: C:\Users\Administrator\.android\build-cache\f86656d601928fb4f5ef98a54bbef1fdefa114a5\output\jars\classes.jar

**Comment by xyzlf** [comment]
你自己的工程里面，也引用了腾讯的jar包吧？

**Comment by love-311** [comment]
是的，有第三方支付的，也是导的一个封装好的。。这个应该怎么处理呢？

**Comment by xyzlf** [comment]
1、你这个冲突是微信的jar冲突了。
2、第三方支付肯定也是用的微信官方开放平台的jar。
3、你可以工程依赖分享库。
4、然后把分享库里面的libammsdk-2.0.jar 删除。
5、 然后引用你的支付jar。这样就共享你支付jar包里面的jar包了。

上面这样说，你能听明白么？  就是分享库可以作为你工程的一个 module。

**Comment by love-311** [comment]
你好，非常感谢你这么用心的帮我解决问题。。我刚刚尝试了删除libammsdk-2.0.jar 之后还是一样的情况呢。。

**Comment by xyzlf** [comment]
Project
       -- app
           build.gradl       ----  引用分享库 
       -- ShareLib
            libs                  ---- 支付jar可以放在这里
            build.gradle    ---- 引用你的支付jar

你只需要clone这个项目，然后导入Module  （shareLibrary）到你的项目中~   希望能帮到你

**Comment by xyzlf** [comment]
Duplicate files copied in APK com/tencent/mm/sdk/platformtools/rep5402863540997075488.tmp

你的问题是这个微信jar包重复了， 删除了，应该就只有一个jar包呀，你Clean一下项目。

**Comment by love-311** [comment]
你好，我可以加下你QQ详细给你说一哈吗。。谢谢。。

**Comment by xyzlf** [comment]
嗯。519578280

**Comment by love-311** [comment]
感谢大神，现在都处理好了。。没有看你的踩坑文章，纠结了半天的微信的分享不了咋回事。。O(∩_∩)O哈哈~

**Comment by xyzlf** [comment]
分享SDK踩过的坑，请参照：http://xyzlf.github.io/2016/07/01/android-share-sdk-1.html

**Comment by love-311** [comment]
发现一个问题，onActivityResult在fragment中回传不了。。

**Comment by xyzlf** [comment]
1、为啥Activity传不到fragment， 你可以网上百度的。
2、这些问题，属于Android基础，已经跟这个库没有关系了。

**Comment by love-311** [comment]
是呀，我看了下你的源码发现了。。不好意思。。

**Comment by zj2050** [comment]
> 1、你这个冲突是微信的jar冲突了。
> 2、第三方支付肯定也是用的微信官方开放平台的jar。
> 3、你可以工程依赖分享库。
> 4、然后把分享库里面的libammsdk-2.0.jar 删除。
> 5、 然后引用你的支付jar。这样就共享你支付jar包里面的jar包了。
> 
> 上面这样说，你能听明白么？ 就是分享库可以作为你工程的一个 module。

删除 libammsdk-2.0.jar 怎么引用支付 lib下面的 jar ？
