### ISSUE TITLE
可以指定某些想要分享的渠道吗？

### ISSUE THREAD

**Issue by love-311** [xyzlf/ShareSDK#7]
如题

**Comment by xyzlf** [comment]
1、很多问问题的，一定是没有看文档，我自认为文档写得比较简洁。

2、这里我还是答复下，以后就不答复了：
如下是指定微信、微信朋友圈的用法：
int channel = ShareConstant.SHARE_CHANNEL_WEIXIN_FRIEND | ShareConstant.SHARE_CHANNEL_WEIXIN_CIRCLE;
ShareUtil.showShareDialog(this, channel, testBean, ShareConstant.REQUEST_CODE);

**Comment by love-311** [comment]
额，sorry，看文档没写所以问了一下。。

**Comment by xyzlf** [comment]
有写的，使用文档最后一条，       第五点 动态配置分享渠道
