### ISSUE TITLE
不添加url 只填 imageurl 无法分享图片 

### ISSUE THREAD

**Issue by careylee0127** [xyzlf/ShareSDK#8]
ShareByWeixin类里面的 buildWXMediaMessage方法， if (TextUtils.isEmpty(data.getUrl()))判断是否少了bitmap==null~ 如果分享图片的时候 ShareEntity填了imageUrl 并没有填Url的时候~ 会直接分享文本~ 而不是图片~

**Comment by xyzlf** [comment]
你是说，分享大图么？？

**Comment by careylee0127** [comment]
哦~ 你分享图片是需要设置setShareBigImg(true) 是吧~ 文档没写~ 我以为分享图片setImageUrl()就可以了额， 总是分享不了~

**Comment by xyzlf** [comment]
嗯嗯。 文档忘记更新了， 稍后更新，重新上传~

**Comment by xyzlf** [comment]
文档已更新~

**Comment by careylee0127** [comment]
tks~
