### ISSUE TITLE
微信分享问题

### ISSUE THREAD

**Issue by OneWolfgang** [xyzlf/ShareSDK#9]
以下是我的分享文本的代码：

        ShareEntity shareBean = new ShareEntity("title", "content.");
        shareBean.setUrl("http://www.xxxx.com");
        int channel = ShareConstant.SHARE_CHANNEL_WEIXIN_FRIEND |     ShareConstant.SHARE_CHANNEL_WEIXIN_CIRCLE | ShareConstant.SHARE_CHANNEL_QQ;
        ShareUtil.showShareDialog(getActivity(), channel, shareBean, ShareConstant.REQUEST_CODE);

当我点击微信分享时，出现错误，错误日志如下：
W/Bundle: Key extra_share_data expected Bundle but value was a com.xyzlf.share.library.bean.ShareEntity.  The default value <null> was returned.
W/Bundle: Attempt to cast generated internal exception:
          java.lang.ClassCastException: com.xyzlf.share.library.bean.ShareEntity cannot be cast to android.os.Bundle
              at android.os.Bundle.getBundle(Bundle.java:739)
              at android.content.Intent.getBundleExtra(Intent.java:5554)
              at com.xyzlf.share.library.ShareDialogActivity.onCreate(ShareDialogActivity.java:44)

请问这个是什么原因呢？QQ分享是正常的。

**Comment by xyzlf** [comment]
转换异常了， ShareEntity 不能转换成 Bundle。  你是直接clone的项目，还是用aar运行的？ 你可以加个断点看下。

**Comment by OneWolfgang** [comment]
aar,我看shareUtil里就是把传递的shareEntity转成bundle了

**Comment by OneWolfgang** [comment]
代码里，shareUtil负责传递Intent的，怎么会出现转换异常呢?

**Comment by xyzlf** [comment]
你用的是 compile ('com.xyzlf.share:sharesdk:0.0.7') 的aar么？ 我自己试了，不会报异常呀。 
只是点击微信，调不起来微信页面。 是因为我这里没添加微信的key。

**Comment by OneWolfgang** [comment]
不是报异常，也是掉不起微信界面，但是我打印了log，发现会出现这个日志。我要分享我自己的网站是http://www.xxx.com，这样的 ，这样的不能分享吗?

**Comment by xyzlf** [comment]
1、能出现分享Dialog， 你打印的日志，就不对，因为界面已经出来了。
2、点击微信调不起微信界面，应该是你没填写微信的key值吧？  需要去微信开放平台申请一个。

**Comment by OneWolfgang** [comment]
微信的key我申请了的，出现了分享dialog，点击分享dialog上的微信图标就出现这个log

**Comment by xyzlf** [comment]
1、你看日志信息，跟你操作的，显然对不上。 ShareDialogActivity是显示的Dialog页面。而你点击微信图标进行分享时，已经进入后续的分享操作了。
2、你之前是不是没设置微信的key，就使用过微信分享？？  
3、你使用的Apk是正式签名的包么？ 不能用debug版本。（如果用过debug版本，你需要清除微信的数据）
4、你参照项目下面分享坑，一一对比下。[分享踩过的坑](http://xyzlf.github.io/2016/07/01/android-share-sdk-1.html)  这个SDK使用的比较成熟了，也有蛮多人用在了自己项目中。

**Comment by OneWolfgang** [comment]
对，之前没有设置过key或者debug下试过，但是签名后同时加上了微信key出现上面的问题。我看过你的文档，是需要清除微信里的数据吗？

**Comment by xyzlf** [comment]
是的， 要清除微信的数据。 之前这个bug，干扰了我一下午的时间.... 但这个应该是微信的某种机制设定的。这个没办法，除非以后微信修改了这类机制....

**Comment by OneWolfgang** [comment]
哦，谢谢了。我再试下。再请教一个问题，在微信分享里String.xml里有个 weixin_redirecturi， 这个uri是指的什么？

**Comment by xyzlf** [comment]
weixin_redirecturi 这个配置没用，已经删除， 已经更新了文档， 谢谢反馈~

**Comment by OneWolfgang** [comment]
好的，谢谢你的分享。

**Comment by xyzlf** [comment]
我去看了下， weixin_redirecturi 这个值， 没用到， 我剔除掉，更新下仓库，避免后面的人使用，也困惑。

**Comment by xyzlf** [comment]
问题解决没？ 解决了，偶就关闭了哈..
